[tool.poetry]
name = "stringeralgorithmsandcv"
version = "0.1.0"
description = ""
authors = ["Color <jgstringer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
