[tool.poetry]
name = "mymath"
version = "0.1.0"
description = "a simple math library"
authors = ["Color <jgstringer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
